import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/Nav'
import Spline from '@splinetool/react-spline';
import BottomBar1 from '../components/BottomBar1';
import Script from 'next/script'

export default function Home() {
  return (
    <>
    <div>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
  
      <div>
        <p>нфлацията се забавя до 14% през март благодарение на по-слаб ръст на цените на храните и спад при горивата, показват данни на НСИ. Понижението спрямо измерените през февруари 16% е най-рязкото, откакто инфлацията премина своя пик в края на миналата година и започна постепенно да се забавя. Сега показателят достига най-ниската си стойност от миналия март, макар да остава в</p>
      </div>
      <div className="mx-4" >
      <iframe className="airtable-embed" src="https://airtable.com/embed/shrcWM2emcSn9OoBK?backgroundColor=yellow&viewControls=on" frameBorder="1" onmouseWheel="" width="80%" height="533"></iframe>

      </div>
      
    
      
     
     
    </div>
    </>
  )
}
