import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/Nav'
import Spline from '@splinetool/react-spline';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <div className="flex justify-center">
      <Image src="/tablet1.png" width={768} height={410}></Image>
      </div>

      
      <div className="h-50% w-50%">
      <Spline scene="https://prod.spline.design/prASHFtxHQ-vcOPN/scene.splinecode" />
    </div>
     
     
    </div>
  )
}
