import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/Nav'
import Spline from '@splinetool/react-spline';
import BottomBar1 from '../components/BottomBar1';
import Script from 'next/script'

export default function Home() {
  return (
    <>
    <div>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <div className="flex justify-center">
      
      <Image src="/tablet1.png" width={768} height={410}></Image>
      
      </div>

      <div >
      <iframe className="airtable-embed" src="https://airtable.com/embed/shrcWM2emcSn9OoBK?backgroundColor=yellow&viewControls=on" frameBorder="0" onmousewheel="" width="100%" height="533"></iframe>

      </div>
      
    
      
     
     
    </div>
    </>
  )
}
